version: '{build}.{branch}'

image: Visual Studio 2017

build:
  verbosity: minimal

build_script:
- ps: ./build.ps1

artifacts:
  - path: 'src\**\Release\*.nupkg'

deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: Fk0aeBW94MCLaMJoq6CB3nQzQu/f0/6Sss0ycZxmh8emZe/zMsehdn+5k75pgb8p